services:
  db:
    image: postgres:16.3-bookworm
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=SuperPassword
      - POSTGRES_USER=RailsUser
      - POSTGRES_DB=rails
  app:
    # image: ghcr.io/scrambledbits/rails-example-main:latest
    build: .
    depends_on:
      db:
        condition: service_completed_successfully
    volumes:
      - appdata:/app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 8080:3000
    environment:
      - DB_PASSWORD=SuperPassword
      - DB_USER=RailsUser
      - DB_NAME=rails_production
      - RAILS_ENV=production
      - SECRET_KEY_BASE='MySuperSecureSecretStringHerePlease!'
      - DB_HOST=db
volumes:
  dbdata:
  appdata:
