services:
  db:
    image: postgres:16.3-bookworm
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "rails" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=SuperPassword
      - POSTGRES_USER=RailsUser
      - POSTGRES_DB=rails
    networks:
      - traefik-network
  app1:
    # image: ghcr.io/scrambledbits/rails-example-main:latest
    build: .
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - appdata:/app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.app1.rule=Host(`app1.sb-proxy.local`)'
      - 'traefik.http.routers.app1.entrypoints=web'
      - 'traefik.http.services.app1.loadbalancer.server.port=3000'
    environment:
      - DB_PASSWORD=SuperPassword
      - DB_USER=RailsUser
      - DB_NAME=rails_production
      - RAILS_ENV=production
      - SECRET_KEY_BASE='MySuperSecureSecretStringHerePlease!'
      - DB_HOST=db
    networks:
      - traefik-network
  app2:
    # image: ghcr.io/scrambledbits/rails-example-main:latest
    build: .
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - appdata:/app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.app2.rule=Host(`app2.sb-proxy.local`)'
      - 'traefik.http.routers.app2.entrypoints=web'
      - 'traefik.http.services.app2.loadbalancer.server.port=3000'
    environment:
      - DB_PASSWORD=SuperPassword
      - DB_USER=RailsUser
      - DB_NAME=rails_production
      - RAILS_ENV=production
      - SECRET_KEY_BASE='MySuperSecureSecretStringHerePlease!'
      - DB_HOST=db
    networks:
      - traefik-network
  app3:
    # image: ghcr.io/scrambledbits/rails-example-main:latest
    build: .
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - appdata:/app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.app3.rule=Host(`app3.sb-proxy.local`)'
      - 'traefik.http.routers.app3.entrypoints=web'
      - 'traefik.http.services.app3.loadbalancer.server.port=3000'
    environment:
      - DB_PASSWORD=SuperPassword
      - DB_USER=RailsUser
      - DB_NAME=rails_production
      - RAILS_ENV=production
      - SECRET_KEY_BASE='MySuperSecureSecretStringHerePlease!'
      - DB_HOST=db
    networks:
      - traefik-network

volumes:
  dbdata:
  appdata:


networks:
  traefik-network:
    external: true
