name: Imagen de Docker RoR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker Login
      uses: docker/login-action@v3.2.0
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: |
        set -x
        docker info
        export IMG_NAME="ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/rails-example-${GITHUB_REF_NAME}:$(date +%s)"
        export IMG_NAME_LATEST="ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/rails-example-${GITHUB_REF_NAME}:latest"
        docker build . --file Dockerfile --tag $IMG_NAME --tag $IMG_NAME_LATEST
        docker push $IMG_NAME
        docker push $IMG_NAME_LATEST
