name: Imagen de Docker RoR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker info
        export IMG_NAME="ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/rails-example-${GITHUB_REF_NAME}:$(date +%s)"
        echo "${GITHUB_TOKEN}" | docker login ghcr.io -u "${GITHUB_ACTOR,,}" --password-stdin
        docker build . --file Dockerfile --tag $IMG_NAME
        docker push $IMG_NAME
              
